"""agregar localidades y ubicación de publicaciones

Revision ID: 06e1be636327
Revises: 766eee72137f
Create Date: 2026-07-25 15:04:32.247590

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '06e1be636327'
down_revision = '766eee72137f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('localities',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('province_id', sa.String(length=2), nullable=False),
    sa.Column('province_name', sa.String(length=100), nullable=False),
    sa.Column('department_id', sa.String(length=5), nullable=True),
    sa.Column('department_name', sa.String(length=150), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=11, scale=8), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=False),
    sa.Column('coordinates', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_localities_coordinates', 'localities', ['coordinates'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_localities_name'), 'localities', ['name'], unique=False)
    op.create_index(op.f('ix_localities_province_id'), 'localities', ['province_id'], unique=False)
    op.create_index(op.f('ix_localities_province_name'), 'localities', ['province_name'], unique=False)
    op.create_index('ix_localities_province_name_name', 'localities', ['province_name', 'name'], unique=False)
    op.add_column('products', sa.Column('locality_id', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_products_locality_id'), 'products', ['locality_id'], unique=False)
    op.create_foreign_key(None, 'products', 'localities', ['locality_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_locality_id'), table_name='products')
    op.drop_column('products', 'locality_id')
    op.drop_index('ix_localities_province_name_name', table_name='localities')
    op.drop_index(op.f('ix_localities_province_name'), table_name='localities')
    op.drop_index(op.f('ix_localities_province_id'), table_name='localities')
    op.drop_index(op.f('ix_localities_name'), table_name='localities')
    op.drop_index('ix_localities_coordinates', table_name='localities', postgresql_using='gist')
    op.drop_table('localities')
    # ### end Alembic commands ###
