"""guardar snapshot bancario en orden

Revision ID: 63c3ab99fea0
Revises: cfff8c361c11
Create Date: 2026-07-26 01:04:53.925146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63c3ab99fea0'
down_revision = 'cfff8c361c11'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('transfer_cbu', sa.String(length=64), nullable=True))
    op.add_column('orders', sa.Column('transfer_alias_bancario', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('transfer_account_holder', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'transfer_account_holder')
    op.drop_column('orders', 'transfer_alias_bancario')
    op.drop_column('orders', 'transfer_cbu')
    # ### end Alembic commands ###
