"""agregar perfil de transportista

Revision ID: 23ff06b57d6d
Revises: 63c3ab99fea0
Create Date: 2026-07-26 11:56:15.302485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23ff06b57d6d'
down_revision = '63c3ab99fea0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_carrier', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('users', sa.Column('carrier_base_locality_id', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('carrier_transport', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('carrier_transport_certified', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('users', sa.Column('carrier_coverage_radius_km', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('users', sa.Column('carrier_capacity', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_carrier_base_locality_id'), 'users', ['carrier_base_locality_id'], unique=False)
    op.create_foreign_key(None, 'users', 'localities', ['carrier_base_locality_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_carrier_base_locality_id'), table_name='users')
    op.drop_column('users', 'carrier_capacity')
    op.drop_column('users', 'carrier_coverage_radius_km')
    op.drop_column('users', 'carrier_transport_certified')
    op.drop_column('users', 'carrier_transport')
    op.drop_column('users', 'carrier_base_locality_id')
    op.drop_column('users', 'is_carrier')
    # ### end Alembic commands ###
