"""agregar transferencias bancarias

Revision ID: cfff8c361c11
Revises: 06e1be636327
Create Date: 2026-07-26 00:24:16.980315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfff8c361c11'
down_revision = '06e1be636327'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE orderstatus ADD VALUE IF NOT EXISTS 'AWAITING_TRANSFER_RECEIPT'")
    op.execute("ALTER TYPE orderstatus ADD VALUE IF NOT EXISTS 'TRANSFER_RECEIPT_SUBMITTED'")
    op.add_column('orders', sa.Column('transfer_receipt_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('cbu', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('alias_bancario', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'alias_bancario')
    op.drop_column('users', 'cbu')
    op.drop_column('orders', 'transfer_receipt_url')
    op.execute(
        "UPDATE orders SET status = 'PLACED' "
        "WHERE status::text IN ('AWAITING_TRANSFER_RECEIPT', 'TRANSFER_RECEIPT_SUBMITTED')"
    )
    op.execute("ALTER TYPE orderstatus RENAME TO orderstatus_old")
    sa.Enum(
        'DRAFT', 'PLACED', 'CONFIRMED', 'PAID', 'SHIPPED',
        'DELIVERED', 'CANCELLED', 'REJECTED',
        name='orderstatus',
    ).create(op.get_bind())
    op.execute(
        "ALTER TABLE orders ALTER COLUMN status TYPE orderstatus "
        "USING status::text::orderstatus"
    )
    op.execute("DROP TYPE orderstatus_old")
    # ### end Alembic commands ###
